### ISSUE TITLE
The dataloader problem

### ISSUE THREAD

**Issue by zeroRains** [fregu856/deeplabv3#16]
I want to know make the 2K image to 1024, then use random crop to make it to 255*255 shape in the train dataloader.Won't this have a bad effect on the results of image segmentation?

**Comment by isJHan** [comment]
> I want to know make the 2K image to 1024, then use random crop to make it to 255*255 shape in the train dataloader.Won't this have a bad effect on the results of image segmentation?

Of course, you can train the Network without cropping. You can try this by modifying the 'DatasetTrain' at line41(maybe) of dataset.py into 'DatasetVal'. When I do this, I found an exception (CUDA out of memory). So, if you have a much powerful GPU, you can feed the original images.
Hope it's the answer you are searching.
